# Project: mainclient
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "main\ client.o" BatalhaNaval.o
LINKOBJ  = "main client.o" BatalhaNaval.o
LIBS     = -L"D:/Arquivos de Programas/Dev-Cpp/MinGW64/lib" -L"D:/Arquivos de Programas/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc "../../../../Arquivos de Programas/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libadvapi32.a" "../../../../Arquivos de Programas/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libmswsock.a" "../../../../Arquivos de Programas/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/libws2_32.a"
INCS     = -I"D:/Arquivos de Programas/Dev-Cpp/MinGW64/include" -I"D:/Arquivos de Programas/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Arquivos de Programas/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Arquivos de Programas/Dev-Cpp/MinGW64/include" -I"D:/Arquivos de Programas/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Arquivos de Programas/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Arquivos de Programas/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = mainclient.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

"main\ client.o": main\ client.cpp
	$(CPP) -c "main client.cpp" -o "main client.o" $(CXXFLAGS)

BatalhaNaval.o: BatalhaNaval.cpp
	$(CPP) -c BatalhaNaval.cpp -o BatalhaNaval.o $(CXXFLAGS)
